version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - 3000:3000
  db:
    image: mysql:5.7.22
    container_name: db
    restart: always
    command: --innodb-use-native-aio=0
    tty: true
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=nodedb
    networks:
      - node-network
    ports:
      - "3306"
    

networks:
 node-network:
    driver: bridge
