version: "3"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: tech3br/laravel:prod
    container_name: laravel
    networks:
      - laranet
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: tech3br/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge

